import Head from "next/head";
import "./../../node_modules/react-draft-wysiwyg/dist/react-draft-wysiwyg.css";
import { useState } from "react";
import { EditorState, convertToRaw } from "draft-js";
import dynamic from "next/dynamic";
import axiosInstance from "@/component/axiosConfig/axiosConfig";
import { useRouter } from "next/router";

export default function Home() {
  const [editorState, setEditorState] = useState(EditorState.createEmpty());
  const router = useRouter();


  const handleSave = () => {
    const contentState = editorState.getCurrentContent();
    const contentStateJson = JSON.stringify(convertToRaw(contentState));
    try {
      axiosInstance
        .post("/api/draft", { content: contentStateJson })
        .then((response) => {
          if (response.data.success) {
            alert("Draft saved successfully");
            router.push("/draft");
          }
        })
        .catch((error) => {
          console.error("Error saving draft", error);
        });
    } catch (error) {
      console.log(error);
    }
    console.log("SAVED !");
  };

  const Editor = dynamic(
    () => import("react-draft-wysiwyg").then((mod) => mod.Editor),
    { ssr: false }
  );
  return (
    <>
      <Head>
        <title>Editor page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <h1>Testing Editor</h1>
      </div>
      <div>
        <Editor
          wrapperClassName="wrapper-class"
          editorClassName="editor-class"
          toolbarClassName="toolbar-class"
          onEditorStateChange={setEditorState}
          editorState={editorState}
        />
        <button onClick={handleSave}>SAVE</button>
      </div>
    </>
  );
}
